config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  # Admin
  namespace :admin do
    get 'letterhead/edit', to: 'letterhead#edit', as: :edit_letterhead
    patch 'letterhead/update', to: 'letterhead#update', as: :update_letterhead
  end
  
  # Appointments
  resources :appointments do
    member do
      patch :begin
      patch :cancel
      patch :reschedule
    end
  end

  # Auth0
  post 'auth/auth0', as: 'authentication'
  get 'auth/auth0/callback', to: 'sessions#callback'
  get 'auth/failure', to: 'sessions#failure'

  # Board applications
  namespace :board_applications do
    resources :land, path: 'land/:application_type', type: /(purchase|sale)/, only: [:create, :new, :index, :show] do
      member do
        get :evaluate
      end
    end

    # Restoration
    def restoration_actions_for(*resources)
      Array(resources).each do |resource|
        self.resources resource do
          self.resources :estimates, module: :restorations
          self.resources :notes, module: :restorations

          member do
            patch 'make-schedulable', to: "#{resource}#make_schedulable"
            patch 'return-to-investigator', to: "#{resource}#return_to_investigator", as: :return_to_investigator
            patch 'send-to-supervisor', to: "#{resource}#send_to_supervisor"
            patch 'upload-application', to: "#{resource}#upload_application", as: :upload_application
            patch 'upload-legal-notice', to: "#{resource}#upload_legal_notice", as: :upload_legal_notice
            patch 'upload-previous', to: "#{resource}#upload_previous", as: :upload_previous
            get 'evaluate', to: "#{resource}#evaluate", as: :evaluate
            get 'review', to: "#{resource}#review", as: :review
            get 'view-application-form', to: "#{resource}#view_application_form", as: :view_application_form
            get 'view-combined', to: "#{resource}#view_combined", as: :view_combined
            get 'view-estimate/:estimate', to: "#{resource}#view_estimate", as: :view_estimate
            get 'view-legal-notice', to: "#{resource}#view_legal_notice", as: :view_legal_notice
            get 'view-previous-report', to: "#{resource}#view_previous_report", as: :view_previous_report
            get 'view-raw-application', to: "#{resource}#view_raw_application", as: :view_raw_application
            get 'view-report', to: "#{resource}#view_report", as: :view_report
          end
        end
      end
    end

    restoration_actions_for :abandonment, :hazardous, :vandalism
    
    namespace :restorations do
      resources :contractors
    end
  end

  # Board Meetings
  resources :board_meetings do
    member do
      patch :finalize_agenda
      get 'board_orders/*filename.pdf', to: 'board_meetings#download_board_orders', as: :download_board_orders
      get '*filename.pdf', to: 'board_meetings#download_agenda', as: :download_agenda
    end
  end

  # Cemeteries
  resources :cemeteries, param: :cemid do
    resources :trustees, except: :index

    collection do
      get 'county/:county(/:options)', to: 'cemeteries#index_by_county', as: :county
      get 'region/:region', to: 'cemeteries#index_by_region', as: :region
      get 'overdue-inspections(/:type(/:region))', to: 'cemeteries#index_with_overdue_inspections', as: :overdue_inspections
    end

    member do
      get 'complaints', to: 'cemeteries#show', defaults: { tab: :complaints }, as: :complaints
      get 'inspect', to: 'cemetery_inspections#perform', as: :inspect
      get 'inspection/:identifier', to: 'cemetery_inspections#show', as: :show_inspection
      patch 'inspection/:identifier/complete', to: 'cemetery_inspections#complete', as: :complete_inspection
      patch 'inspection/:identifier/finalize', to: 'cemetery_inspections#finalize', as: :finalize_inspection
      patch 'inspection/:identifier/revise', to: 'cemetery_inspections#revise', as: :revise_inspection
      patch 'inspection/:identifier/save', to: 'cemetery_inspections#save', as: :save_inspection
      get 'inspection/:identifier/view-full-package', to: 'cemetery_inspections#view_full_package', as: :view_full_inspection_package
      get 'inspection/:identifier/view-report', to: 'cemetery_inspections#view_report', as: :view_inspection_report
      get 'inspections', to: 'cemeteries#show', defaults: { tab: :inspections }, as: :inspections
      post 'inspections/begin', to: 'cemetery_inspections#begin', as: :begin_inspection
      get 'inspections/upload', to: 'cemetery_inspections#upload', as: :upload_inspection
      post 'inspections/upload', to: 'cemetery_inspections#create', as: :create_inspection
      get 'rules', to: 'rules#show', as: :rules
      get 'rules/:date', to: 'rules#show_for_date', as: :rules_by_date
      get 'trustees', to: 'trustees#index', constraints: -> (req) { req.format == :json }, as: :trustees_list
      get 'trustees', to: 'cemeteries#show', defaults: { tab: :trustees }, as: :trustees
    end
  end
  get 'cemetery/:cemid/details.json', to: 'cemeteries#show', as: :cemetery_json

  # Complaints
  resources :complaints do
    resources :attachments, module: :complaints
    resources :notes, module: :complaints

    collection do
      get :all
      get 'user/:user', to: 'complaints#index_by_user', as: :user
    end

    member do
      patch :assign
      patch :begin_investigation
      patch :close
      patch :complete_investigation
      get :investigation_details, to: 'complaints#show', defaults: { tab: :investigation }, as: :investigation
      patch :reassign
      patch :recommend_closure
      patch :reopen_investigation
      patch :request_update
    end
  end
  
  # Crematories
  namespace :crematories do
    resources :retort_models
  end

  resources :crematories, param: :cemid do
    resources :operators, only: [:create, :show, :update]
    resources :retorts, only: [:create, :show, :update]
  end
  
  # Dashboard
  get 'splash', to: 'dashboard#splash', as: :splash
  post 'dashboard/search', to: 'dashboard#search', as: :search
  root 'dashboard#index'

  # Errors
  get '/403', to: 'errors#forbidden'
  get '/500', to: 'errors#internal_server_error'

  # Inspections
  resources :cemetery_inspections, only: :none do
    resources :attachments, module: :cemetery_inspections

    collection do
      get :incomplete
      get :scheduled, to: 'appointments#index'
    end
  end

  # Matters
  resources :matters do
    collection do
      get :schedulable
    end
    
    member do
      patch :schedule
      patch :unschedule
    end
  end

  # Notices
  resources :notices do
    resources :attachments, module: :notices
    resources :notes, module: :notices
    
    member do
      patch :follow_up
      get '*filename.pdf', to: 'notices#download', as: :download
      patch :receive_response
      patch :resolve
    end
  end

  # Notifications
  resources :notifications, only: [] do
    collection do
      patch :mark_all_read
    end
    
    member do
      patch :mark_read
    end
  end

  # PDFs
  #mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  get 'pdfs/embedded/*filename.pdf', to: 'pdf_viewer#show_embedded_pdf', as: :show_embedded_pdf
  
  # Reminders
  resources :reminders do
    member do
      patch :complete
    end
  end

  # Rules
  namespace :rules do
    resources :approvals do
      resources :notes, module: :approvals
      
      resources :revisions do
        patch :receive
      end

      member do
        patch :approve
        patch :assign
        get '*filename.pdf', action: :download_approval_letter, as: :download_approval_letter
        patch :request_revision
        patch :recommend_approval
        patch :upload_revision
        patch :withdraw
      end
    end
  end
  resources :rules

  # Statistics
  get 'statistics/investigator', to: 'statistics#investigator_report'

  # Towns
  get 'towns/county/:county', to: 'towns#index_for_county'

  # Users
  resources :users, only: :none do
    collection do
      get 'team(/:team)', to: 'users#team', as: :team
    end
  end
  get 'user/calendar', to: 'users#calendar', as: :calendar_user
  get 'user/calendar/events', to: 'users#calendar_events', as: :calendar_events_user
  get 'user/change-password', to: 'users#change_password', as: :change_user_password
  get 'user(/:id)/profile', to: 'users#profile', as: :user_profile
  post 'user/update-password', to: 'users#update_password', as: :update_user_password
  get 'logout', to: 'sessions#destroy', as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contractor.rb
# frozen_string_literal: true

class Contractor < ApplicationRecord
  include Locatable
  
  scope :active, -> {
    where(active: true)
  }
  
  def county_name
    COUNTIES[county]
  end
end

app/controllers/board_applications/restorations/contractors_controller.rb
module BoardApplications::Restorations
  class ContractorsController < BoardApplications::RestorationsController
    def create
      @contractor = authorize Contractor.new(contractor_params)
      @contractor.save
    end
    
    def index
      @contractors = authorize Contractor.active
      respond_to do |f|
        f.html
        f.json { 
          render json: @contractors.map { |c| 
            {
              label: c.name, 
              value: c.id 
            } 
          }.to_json 
        }
      end
    end
    
    def show
      @contractor = authorize Contractor.find(params[:id])
      
      respond_to do |f|
        f.json { render json: @contractor.to_json }
      end
    end
    
    def update
      @contractor = authorize Contractor.find(params[:id])
      @contractor.update(contractor_params)
    end
    
    private
    
    def contractor_params
      params.require(:contractor).permit(:city, :county, :name, :phone, :state, :street_address, :zip)
    end
  end
end

app/controllers/board_applications/restorations/estimates_controller.rb
module BoardApplications::Restorations
  class EstimatesController < ApplicationController
    def create
      @estimate = Estimate.new(estimate_params)
      @estimate.restoration_id = params["#{params[:estimate][:restoration_type]}_id"]
      @estimate.contractor = Contractor.find(params[:estimate][:contractor])

      if @estimate.save
        respond_to :js
      end
    end

    private
    
    def estimate_params
      params.require(:estimate).permit(:document, :amount, :warranty, :proper_format)
    end
  end
end

app/controllers/board_applications/restorations/notes_controller.rb
class BoardApplications::Restorations::NotesController < NotesController
  before_action :set_notable

  private
  def set_notable
    @notable = Restoration.find(params[:abandonment_id] || params[:hazardous_id] || params[:vandalism_id])
  end
end

app/controllers/board_applications/restorations_controller.rb
require 'net/http'

module BoardApplications
  class RestorationsController < BoardApplicationsController

    CREATION_EVENT = BoardApplications::BoardApplicationReceivedEvent
    
    def evaluate
      @restoration = model.includes(
        :cemetery,
        :investigator,
        :trustee,
        application_file_attachment: :blob,
        estimates: [:contractor, document_attachment: :blob],
        legal_notice_file_attachment: :blob,
        previous_completion_report_file_attachment: :blob
      ).find(params[:id])
      
      authorize [:board_applications, @restoration]
      @contractors = Contractor.all.order(:name)
      @remaining_letters = ('B'..'Z').to_a
    end

    def index
      if current_user.supervisor?
        @board_applications = model.includes(:cemetery, :status_changes).where(investigator: current_user).or(
            model.includes(:cemetery, :status_changes).evaluated)
      else
        @board_applications = model.includes(:cemetery, :status_changes).where(investigator: current_user)
      end
    end
    
    def make_schedulable
      
      # Update application
      @restoration = model.find(params[:id])
      @restoration.status = :reviewed
      @restoration.recommendation_date ||= Date.current
      @restoration.save
      BoardApplications::BoardApplicationReviewedEvent.new(@restoration, current_user).trigger
      
      redirect_to self.send("board_applications_#{@restoration.type.downcase}_path"), 
        flash: {
          success: 'You have successfully submitted this application.'
        }
    end

    def new
      @board_application = model.new(
        investigator: current_user,
        submission_date: Date.current
      )
      authorize [:board_applications, @board_application]
      @page_info = self.class::PAGE_INFO[:new]
    end

    def return_to_investigator
      @restoration = model.find(params[:id])
      @restoration.update(status: :assigned)
      BoardApplications::BoardApplicationReturnedEvent.new(@restoration, current_user).trigger
      
      redirect_to self.send("board_applications_#{@restoration.type.downcase}_path"),
        flash: {
          success: 'You have successfully returned this application to the assigned investigator.'
        }
    end

    def review
      @restoration = model.includes(estimates: :contractor).find(params[:id])
    end
    
    def send_to_supervisor
      @restoration = model.find(params[:id])

      @restoration.update(
        status: :evaluated,
        recommendation_date: Date.current
      )
      BoardApplications::BoardApplicationEvaluatedEvent.new(@restoration, current_user).trigger
      
      redirect_to self.send("board_applications_#{@restoration.type.downcase}_path"), 
        flash: {  
          success: 'You have successfully submitted this application.'
        }
    end

    def show
      @restoration = model.includes(:cemetery, :investigator, :trustee, estimates: :contractor).find(params[:id])
      authorize [:board_applications, @restoration]
      
      redirect_to self.send("evaluate_board_applications_#{@restoration.type.downcase}_path") if 
        @restoration.assigned? && @restoration.investigator == current_user
    end

    def upload_application
      upload_portion %i(application_file monuments application_form_complete field_visit_date)
    end

    def upload_legal_notice
      upload_portion %i(legal_notice_file legal_notice_newspaper legal_notice_cost legal_notice_format)
    end

    def upload_previous
      upload_portion %i(previous_completion_report_file previous_exists previous_type previous_date)
    end

    def view_application_form
      @restoration = model.find(params[:id])
      @portion = 'Application Form'
      @file = @restoration.application_file
      render 'view_portion'
    end

    def view_combined
      @restoration = model.find(params[:id])

      send_data PDFGenerators::RestorationCombinedPDFGenerator.call(@restoration, self.class::PAGE_INFO[:report][:class]).to_pdf,
        filename: 'Combined Application.pdf',
        type: 'application/pdf',
        disposition: 'inline'
    end

    def view_estimate
      @restoration = model.find(params[:id])
      estimate = @restoration.estimates.find(params[:estimate])
      @portion = "#{estimate.contractor.name} estimate"
      @file = estimate.document
      render 'view_portion'
    end

    def view_legal_notice
      @restoration = model.find(params[:id])
      @portion = 'Legal Notice'
      @file = @restoration.legal_notice_file
      render 'view_portion'
    end

    def view_previous_report
      @restoration = model.find(params[:id])
      @portion = 'Previous Restoration Report'
      @file = @restoration.previous_completion_report_file
      render 'view_portion'
    end

    def view_raw_application
      @restoration = model.find(params[:id])
      @portion = 'Raw Application'
      @file = @restoration.raw_application_file
      render 'view_portion'
    end

    def view_report
      @restoration = model.includes(estimates: :contractor).find(params[:id])

      send_data PDFGenerators::RestorationReportPDFGenerator.call(@restoration, self.class::PAGE_INFO[:report][:class]).render,
        filename: 'Report.pdf',
        type: 'application/pdf',
        disposition: 'inline'
    end

    private

    def upload_portion(keys)
      @restoration = model.find(params[:id])
      @restoration.update(keys.map { |key| [key, params[@restoration.to_sym][key]] }.to_h)
    end
  end
end

app/helpers/restoration_helper.rb
module RestorationHelper
end

app/views/board_applications/restorations/contractors/_contractor_row.html.erb
<tr data-contractor-id="<%= contractor.id %>">
  <td><%= contractor.name %></td>
  <td><%= contractor.county_name %></td>
  <td><%= contractor.formatted_address %></td>
  <td><%= contractor.email.presence || '---' %></td>
  <td><%= contractor.phone.presence || '---' %></td>
  <td class="text-center">
    <%= link_to board_applications_restorations_contractor_path(contractor), 
      data: {
        action: 'board-applications--restorations--contractors--index#openEditContractorForm',
      } do
    %>
      <i class="material-icons tx-18">edit</i>
    <% end %>
  </td>
</tr>

app/views/board_applications/restorations/contractors/_form.html.erb
<%= form_with model: Contractor.new,
  local: false,
  url: board_applications_restorations_contractors_path,
  builder: BracegirdleFormBuilder do |f| 
%>
  <div 
    id="board_applications-restorations-contractors-form-modal" 
    class="modal fade"
    data-controller="board-applications--restorations--contractors--form"
    data-target="board-applications--restorations--contractors--index.formModal"
  >
    <div class="modal-dialog modal-lg w-50" role="document">
      <div class="modal-content">
        <div class="modal-header px-4">
          <h6 
            class="tx-14 mb-0 tx-uppercase tx-inverse tx-bold"
            data-target="board-applications--restorations--contractors--index.formModalTitle"
          >Add New Contractor</h6>
          <button 
            type="button" 
            class="close"
            data-action="board-applications--restorations--contractors--form#close"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body p-4">
          <div class="container-fluid">
            <div class="row">
              <div class="col">
                <%= f.text_field :name, required: true %>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <%= f.text_field :street_address, label: 'Street Address' %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <%= f.text_field :city %>
              </div>
              <div class="col-md-2">
                <%= f.select :state, 
                  options_for_select(STATES, 'NY'), 
                  { without_choices: true },
                  { 
                    data: { 
                      target: 'board-applications--restorations--contractors--form.state' 
                    }
                  }
                %>
              </div>
              <div class="col-md-4">
                <%= f.text_field :zip, label: 'ZIP Code' %>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <%= f.select :county,
                  options_for_select(COUNTIES.invert),
                  { prompt: 'Select county', required: true, without_choices: true },
                  { data: { target: 'board-applications--restorations--contractors--form.county' } }
                %>
              </div>
            </div>
            <div class="modal-footer">
              <button 
                type="button" 
                class="btn btn-secondary"
                data-action="board-applications--restorations--contractors--form#close"
              >Close</button>
              <button 
                class="btn btn-primary"
                data-target="board-applications--restorations--contractors--index.formModalTitle"
              >Add New Contractor</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/board_applications/restorations/contractors/create.js.erb
document.getElementById('board_applications-restorations-contractors-index').dispatchEvent(
  new CustomEvent('bracegirdle:board_applications:restorations:contractors:contractorCreated',
    {
      detail: {
        contractor: '<%= j render(partial: 'contractor_row', locals: { contractor: @contractor }) %>'
      }
    }
  )
);

<% if params['contractor']['estimate_form'] %>
  document.getElementById('board_applications-restorations-estimates-new-modal').dispatchEvent(
    new CustomEvent('bracegirdle:board_applications:restorations:contractors:contractorCreated',
      {
        detail: {
          contractor: '<%= @contractor.id %>'
        }
      }
    )
  );
<% end %>

app/views/board_applications/restorations/contractors/index.html.erb
<% content_for :title, 'Active Contractors' %>
<% content_for :breadcrumbs, breadcrumbs_helper(['Active contractors']) %>
<section
  id="board_applications-restorations-contractors-index"
  class="section-wrapper"
  data-action=
    "bracegirdle:board_applications:restorations:contractors:contractorCreated->board-applications--restorations--contractors--index#contractorCreated
    bracegirdle:board_applications:restorations:contractors:contractorUpdated->board-applications--restorations--contractors--index#contractorUpdated"
  data-controller="board-applications--restorations--contractors--index"
>
  <div 
    class="disappearing-success-message hidden"
    data-target="board-applications--restorations--contractors--index.successMessage"
  >
    <div class="alert alert-success"></div>
  </div>
  <div 
    data-controller="datatable"
    data-target="board-applications--restorations--contractors--index.contractorsDataTable"
  >
    <table
      id="board_applications-restorations-contractors-data-table"
      class="table display responsive no-wrap"
      data-empty-message="There are no contractors to display."
    >
      <thead>
        <tr>
          <th>Name</th>
          <th>County</th>
          <th>Address</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'contractor_row', collection: @contractors, as: :contractor %>
      </tbody>
    </table>
  </div>
  <div class="text-center">
    <button 
      type="button"
      class="btn btn-primary"
      data-action="board-applications--restorations--contractors--index#openNewContractorForm"
      >Add New Contractor</button>
  </div>
  <%= render partial: 'board_applications/restorations/contractors/form' %>
</section>

app/views/board_applications/restorations/contractors/update.js.erb
document.getElementById('board_applications-restorations-contractors-index').dispatchEvent(
  new CustomEvent('bracegirdle:board_applications:restorations:contractors:contractorUpdated',
    {
      detail: {
        contractor: '<%= j render(partial: 'contractor_row', locals: { contractor: @contractor }) %>',
        contractorId: '<%= @contractor.id %>'
      }
    }
  )
);