config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  # Admin
  namespace :admin do
    get 'letterhead/edit', to: 'letterhead#edit', as: :edit_letterhead
    patch 'letterhead/update', to: 'letterhead#update', as: :update_letterhead
  end
  
  # Appointments
  resources :appointments do
    member do
      patch :begin
      patch :cancel
      patch :reschedule
    end
  end

  # Auth0
  post 'auth/auth0', as: 'authentication'
  get 'auth/auth0/callback', to: 'sessions#callback'
  get 'auth/failure', to: 'sessions#failure'

  # Board applications
  namespace :board_applications do
    resources :land, path: 'land/:application_type', type: /(purchase|sale)/, only: [:create, :new, :index, :show] do
      member do
        get :evaluate
      end
    end

    # Restoration
    def restoration_actions_for(*resources)
      Array(resources).each do |resource|
        self.resources resource do
          self.resources :estimates, module: :restorations
          self.resources :notes, module: :restorations

          member do
            patch 'make-schedulable', to: "#{resource}#make_schedulable"
            patch 'return-to-investigator', to: "#{resource}#return_to_investigator", as: :return_to_investigator
            patch 'send-to-supervisor', to: "#{resource}#send_to_supervisor"
            patch 'upload-application', to: "#{resource}#upload_application", as: :upload_application
            patch 'upload-legal-notice', to: "#{resource}#upload_legal_notice", as: :upload_legal_notice
            patch 'upload-previous', to: "#{resource}#upload_previous", as: :upload_previous
            get 'evaluate', to: "#{resource}#evaluate", as: :evaluate
            get 'review', to: "#{resource}#review", as: :review
            get 'view-application-form', to: "#{resource}#view_application_form", as: :view_application_form
            get 'view-combined', to: "#{resource}#view_combined", as: :view_combined
            get 'view-estimate/:estimate', to: "#{resource}#view_estimate", as: :view_estimate
            get 'view-legal-notice', to: "#{resource}#view_legal_notice", as: :view_legal_notice
            get 'view-previous-report', to: "#{resource}#view_previous_report", as: :view_previous_report
            get 'view-raw-application', to: "#{resource}#view_raw_application", as: :view_raw_application
            get 'view-report', to: "#{resource}#view_report", as: :view_report
          end
        end
      end
    end

    restoration_actions_for :abandonment, :hazardous, :vandalism
    
    namespace :restorations do
      resources :contractors
    end
  end

  # Board Meetings
  resources :board_meetings do
    member do
      patch :finalize_agenda
      get 'board_orders/*filename.pdf', to: 'board_meetings#download_board_orders', as: :download_board_orders
      get '*filename.pdf', to: 'board_meetings#download_agenda', as: :download_agenda
    end
  end

  # Cemeteries
  resources :cemeteries, param: :cemid do
    resources :trustees, except: :index

    collection do
      get 'county/:county(/:options)', to: 'cemeteries#index_by_county', as: :county
      get 'region/:region', to: 'cemeteries#index_by_region', as: :region
      get 'overdue-inspections(/:type(/:region))', to: 'cemeteries#index_with_overdue_inspections', as: :overdue_inspections
    end

    member do
      get 'complaints', to: 'cemeteries#show', defaults: { tab: :complaints }, as: :complaints
      get 'inspect', to: 'cemetery_inspections#perform', as: :inspect
      get 'inspection/:identifier', to: 'cemetery_inspections#show', as: :show_inspection
      patch 'inspection/:identifier/complete', to: 'cemetery_inspections#complete', as: :complete_inspection
      patch 'inspection/:identifier/finalize', to: 'cemetery_inspections#finalize', as: :finalize_inspection
      patch 'inspection/:identifier/revise', to: 'cemetery_inspections#revise', as: :revise_inspection
      patch 'inspection/:identifier/save', to: 'cemetery_inspections#save', as: :save_inspection
      get 'inspection/:identifier/view-full-package', to: 'cemetery_inspections#view_full_package', as: :view_full_inspection_package
      get 'inspection/:identifier/view-report', to: 'cemetery_inspections#view_report', as: :view_inspection_report
      get 'inspections', to: 'cemeteries#show', defaults: { tab: :inspections }, as: :inspections
      post 'inspections/begin', to: 'cemetery_inspections#begin', as: :begin_inspection
      get 'inspections/upload', to: 'cemetery_inspections#upload', as: :upload_inspection
      post 'inspections/upload', to: 'cemetery_inspections#create', as: :create_inspection
      get 'rules', to: 'rules#show', as: :rules
      get 'rules/:date', to: 'rules#show_for_date', as: :rules_by_date
      get 'trustees', to: 'trustees#index', constraints: -> (req) { req.format == :json }, as: :trustees_list
      get 'trustees', to: 'cemeteries#show', defaults: { tab: :trustees }, as: :trustees
    end
  end
  get 'cemetery/:cemid/details.json', to: 'cemeteries#show', as: :cemetery_json

  # Complaints
  resources :complaints do
    resources :attachments, module: :complaints
    resources :notes, module: :complaints

    collection do
      get :all
      get 'user/:user', to: 'complaints#index_by_user', as: :user
    end

    member do
      patch :assign
      patch :begin_investigation
      patch :close
      patch :complete_investigation
      get :investigation_details, to: 'complaints#show', defaults: { tab: :investigation }, as: :investigation
      patch :reassign
      patch :recommend_closure
      patch :reopen_investigation
      patch :request_update
    end
  end
  
  # Crematories
  namespace :crematories do
    resources :retort_models
  end

  resources :crematories, param: :cemid do
    resources :operators, only: [:create, :show, :update]
    resources :retorts, only: [:create, :show, :update]
  end
  
  # Dashboard
  get 'splash', to: 'dashboard#splash', as: :splash
  post 'dashboard/search', to: 'dashboard#search', as: :search
  root 'dashboard#index'

  # Errors
  get '/403', to: 'errors#forbidden'
  get '/500', to: 'errors#internal_server_error'

  # Inspections
  resources :cemetery_inspections, only: :none do
    resources :attachments, module: :cemetery_inspections

    collection do
      get :incomplete
      get :scheduled, to: 'appointments#index'
    end
  end

  # Matters
  resources :matters do
    collection do
      get :schedulable
    end
    
    member do
      patch :schedule
      patch :unschedule
    end
  end

  # Notices
  resources :notices do
    resources :attachments, module: :notices
    resources :notes, module: :notices
    
    member do
      patch :follow_up
      get '*filename.pdf', to: 'notices#download', as: :download
      patch :receive_response
      patch :resolve
    end
  end

  # Notifications
  resources :notifications, only: [] do
    collection do
      patch :mark_all_read
    end
    
    member do
      patch :mark_read
    end
  end

  # PDFs
  #mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  get 'pdfs/embedded/*filename.pdf', to: 'pdf_viewer#show_embedded_pdf', as: :show_embedded_pdf
  
  # Reminders
  resources :reminders do
    member do
      patch :complete
    end
  end

  # Rules
  namespace :rules do
    resources :approvals do
      resources :notes, module: :approvals
      
      resources :revisions do
        patch :receive
      end

      member do
        patch :approve
        patch :assign
        get '*filename.pdf', action: :download_approval_letter, as: :download_approval_letter
        patch :request_revision
        patch :recommend_approval
        patch :upload_revision
        patch :withdraw
      end
    end
  end
  resources :rules

  # Statistics
  get 'statistics/investigator', to: 'statistics#investigator_report'

  # Towns
  get 'towns/county/:county', to: 'towns#index_for_county'

  # Users
  resources :users, only: :none do
    collection do
      get 'team(/:team)', to: 'users#team', as: :team
    end
  end
  get 'user/calendar', to: 'users#calendar', as: :calendar_user
  get 'user/calendar/events', to: 'users#calendar_events', as: :calendar_events_user
  get 'user/change-password', to: 'users#change_password', as: :change_user_password
  get 'user(/:id)/profile', to: 'users#profile', as: :user_profile
  post 'user/update-password', to: 'users#update_password', as: :update_user_password
  get 'logout', to: 'sessions#destroy', as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/board_meeting.rb
class BoardMeeting < ApplicationRecord
  attribute :raw_date, :date
  attribute :raw_time, :string
  
  has_many :applications,
    -> { where.not board_application_type: 'Restoration' },
    class_name: 'Matter'
  has_many :matters
  has_many :restorations,
    -> { where board_application_type: 'Restoration' },
    class_name: 'Matter'

  enum status: {
    scheduled: 1,
    agenda_finalized: 2,
    minutes_finalized: 3,
    minutes_approved: 4
  }
  
  validates :date, presence: true
  validates :location, presence: true

  def abandonment_count
    restorations_by_type('Abandonment').count
  end

  def hazardous_count
    restorations_by_type('Hazardous').count
  end

  def date_code
    @date_code ||= date.strftime('%Y–%m')
  end

  def set_matter_identifiers
    letters = ('E'..'Z').to_a
    index = initial_index + 3
    applications.each do |matter|
      matter.update(identifier: "#{date_code}–#{letters.shift}–#{'%02d' % (index += 1)}")
    end
  end

  def to_s
    date.strftime('%B %Y')
  end

  def vandalism_count
    restorations_by_type('Vandalism').count
  end

  private

  def restorations_by_type(type)
    restorations.joins('INNER JOIN restorations ON matters.board_application_id = restorations.id')
      .where(restorations: { type: type })
  end
end

app/controllers/board_meetings_controller.rb
class BoardMeetingsController < ApplicationController
  def create
    @board_meeting = authorize BoardMeeting.new(board_meeting_params)
    @board_meeting.date = Time.parse("#{params[:board_meeting][:raw_date]} #{params[:board_meeting][:raw_time]}")
    @board_meeting.save
    
    redirect_to @board_meeting
  end
  
  def download_agenda
    @board_meeting = authorize BoardMeeting.find(params[:id])

    pdf = AgendaPDF.new(@board_meeting)

    send_data pdf.render,
      filename: "Agenda-#{@board_meeting.date.strftime('%F')}.pdf",
      type: 'application/pdf',
      disposition: 'inline'
  end
  
  def download_board_orders
    @board_meeting = authorize BoardMeeting.includes(matters: [board_application: :cemetery]).find(params[:id])

    send_data PDFGenerators::BoardOrdersPDFGenerator.call(@board_meeting).to_pdf,
      filename: "Agenda-#{@board_meeting.date.strftime('%F')}.pdf",
      type: 'application/pdf',
      disposition: 'inline'
  end

  def finalize_agenda
    @board_meeting = authorize BoardMeeting.find(params[:id])
    @board_meeting.update(status: :agenda_finalized)

    # Set identifiers for matters
    @board_meeting.set_matter_identifiers

    redirect_to @board_meeting, flash: {
      success: 'You have successfully finalized the agenda for this meeting.'
    }
  end

  def index
    @board_meetings = authorize BoardMeeting.all.order(:date)
  end

  def show
    @board_meeting = authorize BoardMeeting.find(params[:id])
  end
  
  private
  
  def board_meeting_params
    params.require(:board_meeting).permit(:location)
  end
end

app/helpers/board_meetings_helper.rb
module BoardMeetingsHelper
end

app/views/board_meetings/_list.html.erb
<section class="section-wrapper">
  <div data-controller="datatable">
    <table 
      id="board-meetings-data-table"
      class="table display responsive no-wrap"
      data-empty-message="There are no board meetings to display."
    >
      <thead>
        <tr>
          <th>Meeting</th>
          <th>Date</th>
          <th>Location</th>
        </tr>
      </thead>
      <tbody>
        <% @board_meetings.each do |board_meeting| %>
          <tr>
            <td>
              <span class="d-none"><%= sort_date(board_meeting.date) %></span>
              <%= link_to board_meeting, board_meeting %>
            </td>
            <td>
              <span class="d-none"><%= sort_date(board_meeting.date) %></span>
              <%= board_meeting.date.strftime('%A, %B %-d, %Y at %R %p') %>
            </td>
            <td><%= board_meeting.location %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if policy(BoardMeeting.new).create? %>
    <div class="mt-4">
      <ul class="nav nav-gray-600 nav-underline justify-content-center">
        <li class="nav-item">
          <button
            type="button"
            class="btn btn-primary"
            data-bs-target="#board_meetings-form-modal"
            data-bs-toggle="modal"
          >Add board meeting</button>
        </li>
      </ul>
    </div>
  <% end %>
</section>
<%= form_with model: BoardMeeting.new(raw_date: Date.current, raw_time: '16:00:00'),
  local: false,
  url: board_meetings_path, 
  builder: BracegirdleFormBuilder do |f| 
%>
  <div 
    id="board_meetings-form-modal" 
    class="modal fade"
  >
    <div class="modal-dialog modal-lg w-60" role="document">
      <div class="modal-content">
        <div class="modal-header px-4">
          <h6 class="tx-14 mb-0 tx-uppercase tx-inverse tx-bold">Add New Board Meeting</h6>
          <button 
            class="close" 
            type="button"
            data-bs-target="#board_meetings-form-modal"
            data-bs-toggle="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body p-4">
          <div class="container-fluid">
            <div class="row">
              <div class="col">
                <%= f.date_field :raw_date, label: 'Date', required: true %>
              </div>
              <div class="col">
                <%= f.time_field :raw_time, label: 'Time', step: 900, required: true %>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <%= f.text_field :location, label: 'Location', required: true %>
              </div>
            </div>
          </div>
          <div class="modal-footer mt-4">
            <button class="btn btn-primary">Add New Board Meeting</button>
            <button 
              type="button" 
              class="btn btn-secondary"
              data-bs-target="#board_meetings-form-modal"
              data-bs-toggle="modal"
            >Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/board_meetings/index.html.erb
<% content_for :title, 'Board Meetings' %>
<% content_for :breadcrumbs, breadcrumbs_helper(['Board meetings']) %>
<%= render partial: 'list' %>

app/views/board_meetings/show.html.erb
<% content_for :title, "#{@board_meeting} Board Meeting" %>
<% content_for :breadcrumbs, 
  breadcrumbs_helper(
    [
      ["Board meetings", board_meetings_path], 
      @board_meeting.to_s
    ]
  )
%>
<div
  id="board_meetings-show"
  data-action="bracegirdle:matters:matterUnscheduled->board-meetings--show#unschedule"
  data-controller="board-meetings--show"
>
  <section class="section-wrapper">
    <div 
      class="disappearing-success-message<%= ' hidden' unless flash[:success] %>"
      data-target="board-meetings--show.successMessage"
    >
      <div class="alert alert-success"><%= flash[:success] %></div>
    </div>
    <table class="table table-striped mt-2">
      <thead>
        <tr>
          <th colspan="2">Meeting Information</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class="w-30" scope="row">Meeting Date</th>
          <td><%= @board_meeting.date.strftime('%A, %B %-d, %Y at %R %p') %></td>
        </tr>
        <tr>
          <th scope="row">Location</th>
          <td><%= @board_meeting.location %></td>
        </tr>
        <tr class="<%= 'd-none' unless @board_meeting.agenda_finalized? %>">
          <th scope="row">Documents</th>
          <td>
            <%= link_to 'Agenda', 
              download_agenda_board_meeting_path(@board_meeting, "Agenda-#{@board_meeting.date.strftime('%F')}")
            %>
            |
            <%= link_to 'Board Orders',
              download_board_orders_board_meeting_path(@board_meeting, "Board-Orders-#{@board_meeting.date.strftime('%F')}")
            %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="form-layout-footer mt-4 ps-4<%= ' d-none' unless @board_meeting.scheduled? %>">
      <%= button_with_confirmation_modal 'Finalize agenda',
        form_action: finalize_agenda_board_meeting_path,
        text: 'Are you sure you want to finalize the agenda for this board meeting?',
        title: 'Finalize Agenda'
      %>
    </div>
  </section>
  <section class="section-wrapper mt-2">
    <label class="section-title mb-4">Restoration</label>
    <div 
      class="disappearing-success-message hidden"
      data-target="board-meetings--show.restorationsSuccessMessage"
    >
      <div class="alert alert-success"></div>
    </div>
    <div 
      data-controller="datatable"
      data-target="board-meetings--show.restorationsDataTableElement"
    >
      <table
        id="board-meeting-restorations-data-table"
        class="table display responsive no-wrap"
        data-empty-message="There are no restoration applications currently scheduled."
      >
        <thead>
          <tr>
            <th></th>
            <th>Application</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @board_meeting.restorations.each_with_index do |restoration, i| %>
            <tr data-matter-id="<%= restoration.id %>">
              <td class="align-middle"><%= i + 1 %></td>
              <td class="align-middle"><%= "#{restoration.cemetery.formatted_name} – #{restoration.board_application.formatted_application_type}" %></td>
              <td class="w-40">
                <% if @board_meeting.scheduled? %>
                  <%= button_with_confirmation_modal 'Unschedule',
                    form_action: unschedule_matter_path(restoration),
                    text: 'Are you sure you want to unschedule this restoration application?',
                    title: 'Unschedule'
                  %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>
  <section class="section-wrapper mt-2">
    <label class="section-title mb-4">Scheduled Matters</label>
    <div 
      class="disappearing-success-message hidden"
      data-target="board-meetings--show.boardApplicationsSuccessMessage"
    >
      <div class="alert alert-success"></div>
    </div>
    <div
      data-controller="datatable"
      data-target="board-meetings--show.boardApplicationsDataTableElement"
    >
      <table
        id="board-meeting-agenda-data-table"
        class="table display responsive no-wrap"
        data-empty-message="There are no matters currently scheduled."
      >
        <thead>
          <tr>
            <th></th>
            <th>Matter</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @board_meeting.applications.each_with_index do |matter, i| %>
            <tr data-matter-id="<%= matter.id %>">
              <td class="align-middle"><%= i + 1 %></td>
              <td class="align-middle"><%= "#{matter.cemetery.formatted_name} – #{matter.application.formatted_application_type}" %></td>
              <td>
                <% if @board_meeting.scheduled? %>
                  <%= button_with_confirmation_modal 'Unschedule',
                    form_action: unschedule_matter_path(matter),
                    text: 'Are you sure you want to unschedule this application?',
                    title: 'Unschedule'
                  %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>
</div>